pre-commit rewrited from python to bash

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,22 +1,11 @@
-#!/usr/bin/env python
+#!/bin/sh
 
-import subprocess
-import sys
+python tests.py
 
-
-def main():
-    print('-----> running pre-commit unit tests')
-    proc = subprocess.Popen(['python', 'tests.py'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
-    _, err = proc.communicate()
-    err = str(err, 'utf-8')
-    print(err)
-
-    if 'FAILED' in err:  # we have to abort this commit
-        print('-----> code did not pass the unit tests, aborting commit')
-        sys.exit(1)
-    else:
-        sys.exit(0)
-
-
-if __name__ == '__main__':
-    main()
+if [[ $? != 0 ]] ;
+then
+    echo 'unit tests failed, commit is not possible'
+    exit 1
+else
+    echo 'unit tests passed'
+fi
