pre-commit rewrited from python to bash

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,11 +1,12 @@
-#!/bin/sh
+#!/bin/bash
 
 python tests.py
 
-if [[ $? != 0 ]] ;
+if [ $? -eq 0 ] 
 then
-    echo 'unit tests failed, commit is not possible'
-    exit 1
+    echo "unit tests passed, commit is allowed"
+    exit 0
 else
-    echo 'unit tests passed'
+    echo "unit tests failed, commit is not possible"
+    exit 1
 fi
